### ISSUE TITLE
 [Feature Request] Add Support for open banking aggregator GoCardless

### ISSUE THREAD

**Issue by dev590t** [jbms/finance-dl#101]
redirected from https://github.com/jbms/beancount-import/issues/240

web scraping isn't the ideal approach to ingest data from bank accounts.

Using an open banking aggregator instead of web scraping offers several advantages, especially in terms of reliability, security, compliance, and efficiency. Here are some key reasons why using an open banking aggregator is generally better than web scraping:

### 1. **Reliability and Stability**
- **Open Banking**: Open banking APIs are designed to be reliable and stable, providing consistent access to financial data.
- **Web Scraping**: Web scraping relies on the structure of web pages, which can change frequently, leading to broken scrapers and unreliable data.

### 2. **Security**
- **Open Banking**: Open banking APIs use secure, standardized authentication methods (such as OAuth 2.0) to ensure that data is accessed securely.
- **Web Scraping**: Web scraping often involves storing and using user credentials, which can pose significant security risks if not handled properly.

### 3. **Compliance**
- **Open Banking**: Open banking APIs are compliant with regulations such as PSD2 in the EU, ensuring that data is accessed and used in a legal and compliant manner.
- **Web Scraping**: Web scraping may violate terms of service and can lead to legal issues, as it often involves accessing data in ways that are not authorized by the data provider.

### 4. **Data Quality**
- **Open Banking**: Open banking APIs provide structured, standardized data, making it easier to process and analyze.
- **Web Scraping**: Web scraping can result in inconsistent and unstructured data, which requires additional processing and cleaning.

### 5. **Efficiency**
- **Open Banking**: Open banking APIs are designed to be efficient, providing quick and easy access to financial data.
- **Web Scraping**: Web scraping can be slow and resource-intensive, as it involves parsing and extracting data from web pages.

### 6. **Scalability**
- **Open Banking**: Open banking APIs are designed to handle large volumes of data and can scale to meet the needs of growing applications.
- **Web Scraping**: Web scraping can be difficult to scale, as it often involves managing multiple scrapers and dealing with rate limits and IP blocking.

### 7. **Maintenance**
- **Open Banking**: Open banking APIs are maintained by the financial institutions, reducing the need for ongoing maintenance by the user.
- **Web Scraping**: Web scraping requires ongoing maintenance to adapt to changes in web page structure and to handle issues such as rate limits and IP blocking.

### 8. **User Experience**
- **Open Banking**: Open banking APIs provide a seamless and secure user experience, allowing users to grant and revoke access to their financial data easily.
- **Web Scraping**: Web scraping can lead to a poor user experience, as it often involves sharing credentials and dealing with security and compliance issues.

### 9. **Bigger bank coverage**
- **Open Banking**: Open banking APIs can cover over thousands bank institutions.
- **finance-dl**: finance-dl covers less I think

GoCardless supports many PSD2-compliant banks in the EU and the UK, and it is free to use. It supports [over 2500 banks](https://gocardless.com/bank-account-data/coverage/). The open-source accounting software Firefly III already integrates with some free open banking APIs. For more information, you can visit the [Firefly III Documentation](https://docs.firefly-iii.org/how-to/data-importer/import/gocardless/). Beancount ecosystem is still lagging in this domain.

Adding support for GoCardless would be a great enhancement.

**Comment by jbms** [comment]
We'd definitely be open to adding that as an additional data source.

**Comment by dev590t** [comment]
I discover the project [tarioch/beancounttools](https://github.com/tarioch/beancounttools) it includes a beancount importer for Nordigen (which is the former name of the banking api provider of GoCardless).

It works with bean-extract. I could even configure it to work with smart_importer:
```
from smart_importer import apply_hooks, PredictPostings
from tariochbctools.importers.nordigen import importer as nordimp

CONFIG = [
    apply_hooks(nordimp.Importer(), [PredictPostings()]),
]
```

**Comment by Zburatorul** [comment]
It sounds like the problem is solved then? The workflow if I understand correctly is you download with Nordigen and import with the beancounttools project.

**Comment by dev590t** [comment]
> The workflow if I understand correctly is you download with Nordigen and import with the beancounttools project.

Yes, 

bean-extract ecosystem has this library to import the data from Nordigen. I think I can close the issue.
