### ISSUE TITLE
Error on OFX account with no transactions

### ISSUE THREAD

**Issue by witten** [jbms/finance-dl#18]
### Background

I opened a new account at an institution, but I haven't funded it yet. Meaning that it has no transactions whatsoever. However, I'm running `finance-dl` anyway, because I have other accounts at the same institution whose transactions I'd like to fetch. When I run `fintance-dl` to fetch transactions from this institution via OFX, I get an error:

```console
$ python3 -m finance_dl.update --config-module finance_dl_config --log-dir logs update institution --force
```

### Actual behavior

Here's the tail end of the traceback I get:

```console
...
[0/1] institution [41s elapsed]   File "/usr/lib/python3.7/site-packages/finance_dl/ofx.py", line 187, in get_earliest_data
[0/1] institution [41s elapsed]     account.number)
[0/1] institution [41s elapsed] RuntimeError: Failed to retrieve any data for account: 12345678
[1/1] institution [41s elapsed] FAILED with return code 1
```

### Expected behavior

Maybe logging/warning that there are no transactions for that account, and merrily continuing onward to the other accounts. I'm open to ideas about what right behavior here is!

**Comment by jbms** [comment]
Logging and continuing sounds like the right behavior.  If you are able to produce a patch that would be great!

**Comment by witten** [comment]
Done!
