### ISSUE TITLE
support Takeout for Google Purchases import

### ISSUE THREAD

**Issue by riking** [jbms/finance-dl#3]
Steps to produce a Takeout:

 - https://takeout.google.com/settings/takeout
 - "Select None"
 - Scroll down to "Purchases & Reservations" and turn it on
 - Next, pick zip or .tgz, email is fine
 - Should be fairly fast

Extracts to `Takeout/Purchases _ Reservations/order_##########.json` and contains the extracted ordering information.

**Comment by jbms** [comment]
Thanks for pointing this out.  The JSON this produces is nicer than the data than can be extracted from the HTML pages (which is also in JSON format, but lacks field names and presumably is more likely to change).  

The HTML is useful as well, though, as it provides a formatted representation to display to the user without the need to recreate it from the JSON.  Perhaps it would be useful to retrieve both.

Would you be interested in trying to implement this?

**Comment by jbms** [comment]
This is implemented in 7efb5db606cbc77fecc884eddf423127cd83460e.

**Comment by riking** [comment]
Thanks, great!
