### ISSUE TITLE
Please document requirements

### ISSUE THREAD

**Issue by philipsd6** [jbms/finance-dl#4]
It would be nice to have the requirements documented, with examples for the most common systems. I'm having trouble getting this to work on my XUbuntu VM after installing it in my beancount virtualenv:

    selenium.common.exceptions.WebDriverException: Message: 'chromedriver_wrapper.py' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

There's no description for how #1 was solved. I tried installing `google-chrome-beta`, `google-chrome-stable`, as well as the chromium snap, and `chromium` from the ubuntu repositories. I also tried installing `chromedriver` and it's dependencies:

    sudo apt-get install chromium-chromedriver

And still, same error. I'm not sure how to get this working.

**Comment by jbms** [comment]
There was a problem in how the chromedriver_wrapper.py script was being installed, such that installing in "develop" mode worked but regular installation did not.  Please let me know if the referenced commit does not solve the problem for you, or if you run into any other issues.
